<?php
/**
 * @var \App\Block\RenderBlock $this
 * @var string $block
 */
?>

<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="/src/image/icon.png">
    <link href="https://fonts.cdnfonts.com/css/days-2" rel="stylesheet">
    <link href="https://fonts.cdnfonts.com/css/videopac" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/src/css/neon/neon-text.css">
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/src/assets/bower_components/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/src/assets/bower_components/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="/src/assets/bower_components/magnific-popup/dist/magnific-popup.css" />
    <link rel="stylesheet" type="text/css" href="/src/assets/youplay/css/youplay.min.css" />
    <link rel="stylesheet" type="text/css" href="/src/assets/youplay/css/youplay-anime.min.css" />
    <link rel="stylesheet" type="text/css" href="/src/css/common/common.css" />
    <link rel="stylesheet" type="text/css" href="/src/css/pushbutton/pushbutton.css">
    <link rel="stylesheet" type="text/css" href="/src/css/background/background.css">
    <link rel="stylesheet" type="text/css" href="/src/css/shop/shop.css">
</head>
<body>
    <div class="page-preloader preloader-wrapp">
        <img src="src/image/logo.png" alt="">
        <div class="preloader"></div>
    </div>

    <nav class="navbar-youplay navbar navbar-default navbar-fixed-top navbar-small">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">
                    <img src="../../src/image/logo.png" alt="">
                </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <button
                            class="pushbutton__glow-on-hover"
                            onclick="window.location.href = '/'"
                        >
                            Главная страница
                        </button>
                    </li>
                    <li>
                        <button
                            class="pushbutton__glow-on-hover"
                            onclick="window.location.href = '/player'"
                        >
                            Личный кабинет
                        </button>
                    </li>
                    <li>
                        <button
                            class="pushbutton__glow-on-hover"
                            onclick="window.location.href = '/library'"
                        >
                            Библиотека
                        </button>
                    </li>
                    <li>
                        <button
                            class="pushbutton__glow-on-hover"
                            onclick="window.location.href = '/shop'"
                        >
                            Магазин
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <?php $this->renderBlock($block); ?>

    <footer class="youplay-footer-parallax">
        <div
            class="wrapper"
            style="background-image: url('/src/image/footer-bg-profile.jpg')"
        >
            <div class="social">
                <div class="container">
                    <h3>Социальные сети <strong>Orion Games</strong></h3>

                    <div class="social-icons">
                        <div class="social-icon">
                            <a
                                href="https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley"
                                target="_blank"
                            >
                                <img
                                    class="fa fa-youtube"
                                    src="https://cdn141.picsart.com/327737999037201.jpg"
                                    width="72px"
                                    height="72px"
                                    alt="">
                                <span>Смотрите на ютубе</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="copyright">
                <div class="container">
                    <strong>Orion Games</strong> &copy; 2023. Все права защищены
                </div>
            </div>
        </div>
    </footer>

    <script type="text/javascript" src="/src/assets/bower_components/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="/src/assets/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/src/assets/youplay/js/youplay.min.js"></script>
    <script type="text/javascript" src="/src/js/init-page.js"></script>
</body>
</html>