<?php
/**
 * @var \App\Block\AdminGamesBlock $this
 */
?>
<html lang="en">
<head>
    <title>Список игр</title>
</head>
<body>
<section class="content-wrap">
    <section class="youplay-banner banner-top big youplay-banner-parallax background__anime_admin">
        <div class="info">
            <div>
                <div class="container">
                    <div class="main-text neon-text">
                        Список игр
                    </div>
                </div>
            </div>
        </div>
        <div class="youplay-user-navigation">
            <div class="container">
                <ul>
                    <li class="active">
                        <a href="/admin-games">Список игр</a>
                    </li>
                    <li>
                        <a href="/newgame">Добавить игру</a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

    <div class="youplay-content">
        <section class="youplay-features container shop">
            <?php $i = 0; foreach($this->getGames() as $game): ?>
            <?php if ($i == 3): ?>
                </section>
                <section class="youplay-features container shop">
            <?php $i = 0; endif; ?>
                <a <?= 'href=/admin-game?id=' . $game['id'] ?>>
                <div class="col-md-3 col-xs-12 shop__element">
                    <div class="feature angled-bg">
                        <h3><?= $game['name'] ?></h3>
                    </div>
                </div>
                </a>
            <?php $i++; endforeach; ?>
        </section>
    </div>

</section>
</body>
</html>
