<?php
/**
 * @var \App\Block\AdminPlayersBlock $this
 */
?>
<html lang="en">
<head>
    <title>Главная страница</title>
</head>
<body>
    <section class="content-wrap">
        <section class="youplay-banner banner-top big youplay-banner-parallax background__anime_admin">
            <div class="info">
                <div>
                    <div class="container">
                        <div class="main-text neon-text">
                            Players
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="youplay-content">
            <section class="youplay-features container shop">
                <?php $i = 0; foreach($this->getAllPlayer() as $player): ?>
                <?php if ($i == 3): ?>
            </section>
            <section class="youplay-features container shop">
                <?php $i = 0; endif; ?>
                <a <?= 'href=/edit-player?id=' . $player['id'] ?>>
                    <div class="col-md-3 col-xs-12 shop__element">
                        <div class="feature angled-bg">
                            <h3><?= $player['username'] ?></h3>
                        </div>
                    </div>
                </a>
                <?php $i++; endforeach; ?>
            </section>
        </div>
    </section>
</body>
</html>