<?php
/**
 * @var \App\Block\CompaniesBlock $this
 */
?>
<html lang="en">
<head>
    <title>Магазин</title>
</head>
<body>
<section class="content-wrap">
    <section class="youplay-banner banner-top big youplay-banner-parallax background__anime_admin">
        <div class="info">
            <div>
                <div class="container">
                    <div class="main-text neon-text">
                        Список компаний
                    </div>
                </div>
            </div>
        </div>
        <div class="youplay-user-navigation">
            <div class="container">
                <ul>
                    <li class="active">
                        <a href="/companies">Список компаний</a>
                    </li>
                    <li>
                        <a href="/newcompany">Добавить компанию</a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

    <div class="youplay-content">
        <section class="youplay-features container shop">
            <?php $i = 0; foreach($this->getAllCompanies() as $company): ?>
            <?php if ($i == 3): ?>
                </section>
                <section class="youplay-features container shop">
            <?php $i = 0; endif; ?>
                <a <?= "href=/edit-company?id=" . $company['id'] ?>>
                <div class="col-md-3 col-xs-12 shop__element">
                    <div class="feature angled-bg">
                        <h3><?= $company['name'] ?></h3>
                    </div>
                </div>
                </a>
            <?php $i++; endforeach; ?>
        </section>
    </div>

</section>
</body>
</html>
