<?php
/**
 * @var \App\Block\EditPlayerBlock $this
 */
$player = $this->getPlayerInfo();
?>

<html>
<head>
    <title>Изменить информацию</title>
</head>
<body>
    <section class="content-wrap">
        <div class="youplay-banner banner-top youplay-banner-parallax small">
            <div class="image" style="background-image: url('/src/image/banner-blog-bg.jpg')">
            </div>

            <div class="info">
                <div>
                    <div class="container">
                        <h1 class="neon-text main-text">Изменить информацию об игроке</h1>
                    </div>
                </div>
            </div>

            <div class="youplay-user-navigation">
                <div class="container">
                    <ul>
                        <li>
                            <a <?= 'href=/player?id=' . htmlspecialchars($player->getId()) ?>>
                                Профиль
                            </a>
                        </li>
                        <li>
                            <a <?= 'href=/library?id=' . htmlspecialchars($player->getId()) ?>>
                                Библиотека
                            </a>
                        </li>
                        <li class="active">
                            <a <?= 'href=/edit-player?id=' . htmlspecialchars($player->getId()) ?>>
                                Изменить информацию
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container youplay-content">
            <h2 class="mt-0">Информация об игроке</h2>
            <p>
            <form action="/update-player" method="post">
                <div class="youplay-input">
                    <input
                            type="hidden"
                            name="csrf_token"
                            value="<?= htmlspecialchars($this->getCsrfToken()) ?>"
                    >
                </div>
                <div class="youplay-input">
                    <input
                            type="hidden"
                            name="id"
                            value="<?= htmlspecialchars($player->getId()) ?>"
                    >
                </div>
                <div class="youplay-input">
                    <input
                            type="text"
                            name="name"
                            value="<?= htmlspecialchars($player->getName()) ?>"
                            placeholder="Имя"
                    >
                </div>
                <div class="youplay-input">
                    <input
                            type="text"
                            name="surname"
                            value="<?= htmlspecialchars($player->getSurname()) ?>"
                            placeholder="Фамилия"
                    >
                </div>
                <div class="youplay-input">
                    <input
                            type="text"
                            name="username"
                            value="<?= htmlspecialchars($player->getUsername()) ?>"
                            placeholder="Ник"
                    >
                </div>
                <div class="youplay-input">
                    <input
                            type="email"
                            name="mail"
                            value="<?= htmlspecialchars($player->getMail()) ?>"
                            placeholder="Email"
                    >
                </div>
                <div class="youplay-input">
                    <input
                            type="hidden"
                            name="fake_hour"
                            value="<?= htmlspecialchars($player->getFakeHour()) ?>"
                    >
                </div>
                <div class="youplay-input">
                    <input
                            type="hidden"
                            name="is_admin"
                            value="<?= htmlspecialchars($player->getIsAdmin()) ?>"
                    >
                </div>
                <button class="btn btn-default db">Сохранить</button>
            </form>
            <button
                    class="btn btn-default db"
                <?= "href=/delete-player?id=" . htmlspecialchars($player->getId()) ?>
            >
                Удалить
            </button>
            </p>
        </div>
    </section>
</body>
</html>