<?php
/**
 * @var \App\Block\ErrorBlock $this
 */
?>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale-1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Не найдено</title>
    <link href="https://fonts.cdnfonts.com/css/days-2" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/src/css/error-404/error-404.css">
</head>
<body class="error-404__background">
    <div class="error-404__header">Ошибка</div>
    <div class="error-404__text">
        <?= $this->protectFromXss($this->getMessage()) ?>
    </div>
    <br>
    <div class="error-404__text">
        <a class="error-404__link" href="/">Вернуться</a>
    </div>
</body>
</html>