<?php
/**
 * @var \App\Block\GameBlock $this
 */

$comments = $this->getComments();
$childComments = $this->getChildComments();
?>

<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Игры</title>

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.cdnfonts.com/css/days-2" rel="stylesheet">
    <link href="https://fonts.cdnfonts.com/css/videopac" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/src/css/neon/neon-text.css">
    <link rel="icon" type="image/png" href="/src/image/icon.png">
    <link href='https://fonts.googleapis.com/css?family=Passion+One|Cantarell:400,400italic,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/src/assets/bower_components/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/src/assets/bower_components/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="/src/assets/bower_components/magnific-popup/dist/magnific-popup.css" />
    <link rel="stylesheet" type="text/css" href="/src/assets/bower_components/social-likes/dist/social-likes_flat.css" />
    <link rel="stylesheet" type="text/css" href="/src/assets/youplay/css/youplay-anime.min.css" />
    <link rel="stylesheet" type="text/css" href="/src/css/common/common.css" />
    <link rel="stylesheet" type="text/css" href="/src/css/pushbutton/pushbutton.css">
    <link rel="stylesheet" type="text/css" href="/src/css/background/background.css">
</head>
<body>

<div class="page-preloader preloader-wrapp">
    <img src="src/image/logo.png" alt="">
    <div class="preloader"></div>
</div>

<nav class="navbar-youplay navbar navbar-default navbar-fixed-top navbar-small">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">
                <img src="../../src/image/logo.png" alt="">
            </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <button
                            class="pushbutton__glow-on-hover"
                            onclick="window.location.href = '/'"
                    >
                        Главная страница
                    </button>
                </li>
                <li>
                    <button
                            class="pushbutton__glow-on-hover"
                            onclick="window.location.href = '/player'"
                    >
                        Личный кабинет
                    </button>
                </li>
                <li>
                    <button
                            class="pushbutton__glow-on-hover"
                            onclick="window.location.href = '/library'"
                    >
                        Библиотека
                    </button>
                </li>
                <li>
                    <button
                            class="pushbutton__glow-on-hover"
                            onclick="window.location.href = '/game'"
                    >
                        Игры
                    </button>
                </li>
            </ul>
        </div>
    </div>
</nav>

<section class="content-wrap">
    <section class="youplay-banner banner-top big youplay-banner-parallax background_anime">
        <div class="info">
            <div>
                <div class="container">
                    <div class="main-text neon-text">
                        <?= $this->getGameName() ?>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="container youplay-news youplay-post">
        <div class="col-md-9">
            <article class="news-one">
                <div class="description">
                    <a
                        href="https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley"
                        class="angled-img pull-left video-popup"
                        target="_blank"
                    >
                        <div class="img">
                            <img src="src/image/game-brs-1-500x375.jpg" alt="">
                        </div>
                        <i class="fa fa-play icon"></i>
                    </a>
                    <p>
                        <?= $this->getGameDescription() ?>
                    </p>
                </div>
                <div class="tags">
                    <i class="fa fa-tags"></i>
                    <a href="#">Release</a>,
                    <a href="#"><?= $this->getGameName() ?></a>,
                    <a href="#">Windows</a>
                </div>
                <div class="meta">
                    <div class="item">
                        <i class="fa fa-user meta-icon"></i>
                        Автор: <a href="#!"><?= $this->getCompanyName() ?></a>
                    </div>
                    <div class="item">
                        <i class="fa fa-calendar meta-icon"></i>
                        Вышла: <a href="#!">14 Мая, 2016</a>
                    </div>
                    <div class="item">
                        <i class="fa fa-bookmark meta-icon"></i>
                        Состояние: <a href="#!">Релиз</a>
                    </div>
                </div>
            </article>
            <div class="comments-block">
                <h2>Комментарии <small>(2)</small></h2>
                <ul class="comments-list">
                    <?php foreach ($comments as $comment): ?>
                    <li>
                        <article>
                            <div class="comment-avatar pull-left">
                                <img src="src/image/avatar-user-1.png" alt="">
                            </div>
                            <div class="comment-cont clearfix">
                                <a class="comment-author h4" href="#!"><?= $comment['player'] ?></a>
                                <div class="date">
                                    <?= $comment['time'] ?>
                                    <a href="#!" class="pull-right"><i class="fa fa-reply"></i> Ответить</a>
                                </div>
                                <div class="comment-text">
                                    <?= $comment['text'] ?>
                                </div>
                            </div>
                        </article>

                        <ul class="child-comment">
                            <?php foreach ($childComments as $childComment): ?>
                            <li>
                                <article>
                                    <div class="comment-avatar pull-left">
                                        <img src="src/image/avatar.png" alt="">
                                    </div>
                                    <div class="comment-cont clearfix">
                                        <a class="comment-author h4" href="#!"><?= $childComment['player'] ?></a>
                                        <div class="date">
                                            <?= $childComment['time'] ?>
                                            <a href="#!" class="pull-right"><i class="fa fa-reply"></i> ответить</a>
                                        </div>
                                        <div class="comment-text">
                                            <?= $childComment['text'] ?>
                                        </div>
                                    </div>
                                </article>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                    <?php endforeach; ?>
                </ul>

                <h2>Оставить комментарий</h2>
                <form action="#!" class="comment-form">
                    <div class="comment-cont clearfix">
                        <div class="youplay-textarea">
                            <textarea
                                    name="message"
                                    rows="5"
                                    placeholder="Your Comment..."
                            >
                            </textarea>
                        </div>
                        <button class="btn btn-default pull-right">Отправить</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="col-md-3">
            <div class="side-block">
                <h4 class="block-title">Компания</h4>
                <ul class="block-content">
                    <li><a href="#!"><?= $this->getCompanyName() ?></a>
                    </li>
                </ul>
            </div>

            <div class="side-block">
                <h4 class="block-title">Жанр</h4>
                <ul class="block-content">
                    <li>
                        <a href="#!"><?= $this->getGenre() ?></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <footer class="youplay-footer-parallax">
        <div
                class="wrapper"
                style="background-image: url('/src/image/footer-bg.jpg')"
        >
            <div class="social">
                <div class="container">
                    <h3>Социальные сети <strong>Orion Games</strong></h3>

                    <div class="social-icons">
                        <div class="social-icon">
                            <a
                                    href="https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley"
                                    target="_blank"
                            >
                                <img
                                        class="fa fa-youtube"
                                        src="https://cdn141.picsart.com/327737999037201.jpg"
                                        width="72px"
                                        height="72px"
                                        alt="">
                                <span>Смотрите на ютубе</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="copyright">
                <div class="container">
                    <strong>Orion Games</strong> &copy; 2023. Все права защищены
                </div>
            </div>
        </div>
    </footer>
</section>

<script type="text/javascript" src="/src/assets/bower_components/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="/src/assets/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/src/assets/youplay/js/youplay.min.js"></script>
<script type="text/javascript" src="/src/js/init-page.js"></script>

</body>
</html>
