<?php
/**
 * @var \App\Block\GameBlock $this
 */
$game = $this->getGameInfo();
$comments = $this->getParentComments();
$childComments = $this->getChildComments();
?>

<html>
<head>
    <title>Игра</title>
</head>
<body>
<section class="content-wrap">
    <section class="youplay-banner banner-top big youplay-banner-parallax background_anime">
        <div class="info">
            <div>
                <div class="container">
                    <div class="main-text neon-text">
                        <?= $this->protectFromXss($game->getName()) ?>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="container youplay-news youplay-post">
        <div class="col-md-9">
            <article class="news-one">
                <div class="description">
                    <a
                        href="https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley"
                        class="angled-img pull-left video-popup"
                        target="_blank"
                    >
                        <div class="img">
                            <img src="/image/game-brs-1-500x375.jpg" alt="">
                        </div>
                        <i class="fa fa-play icon"></i>
                    </a>
                    <p>
                        <?= $this->protectFromXss($game->getDescription()) ?>
                    </p>
                </div>
                <div class="tags">
                    <i class="fa fa-tags"></i>
                    <a href="#">Release</a>,
                    <a href="#"><?= $this->protectFromXss($game->getName()) ?></a>,
                    <a href="#">Windows</a>
                </div>
                <div class="meta">
                    <div class="item">
                        <i class="fa fa-user meta-icon"></i>
                        Автор: <a href="#!"><?= $this->protectFromXss($game->getName()) ?></a>
                    </div>
                    <div class="item">
                        <i class="fa fa-calendar meta-icon"></i>
                        Вышла: <a href="#!"><?= $this->protectFromXss($game->getYearOfRelease()) ?></a>
                    </div>
                    <div class="item">
                        <i class="fa fa-bookmark meta-icon"></i>
                        Состояние: <a href="#!">Релиз</a>
                    </div>
                </div>
            </article>
            <div class="comments-block">
                <h2>
                    Комментарии
                    <small>
                        <?= sizeof($comments) + sizeof($childComments) ?>
                    </small>
                </h2>
                <ul class="comments-list">
                    <?php foreach ($comments as $comment): ?>
                        <li>
                            <article>
                                <div class="comment-avatar pull-left">
                                    <img src="/image/avatar-user-1.png" alt="">
                                </div>
                                <div class="comment-cont clearfix">
                                    <a class="comment-author h4" href="#!">
                                        <?= $this->protectFromXss($comment->getUsername()) ?>
                                    </a>
                                    <div class="date">
                                        <?= $this->protectFromXss($comment->getDateOfWriting()) ?>
                                        <a href="#!" class="pull-right"><i class="fa fa-reply"></i> Ответить</a>
                                    </div>
                                    <div class="comment-text">
                                        <?= $this->protectFromXss($comment->getTextOfComment()) ?>
                                    </div>
                                </div>
                            </article>

                            <ul class="child-comment">
                                <?php foreach ($childComments as $childComment): ?>
                                    <?php if ($childComment->getParentComment() == $comment->getId()): ?>
                                        <li>
                                            <article>
                                                <div class="comment-avatar pull-left">
                                                    <img src="/image/avatar.png" alt="">
                                                </div>
                                                <div class="comment-cont clearfix">
                                                    <a class="comment-author h4" href="#!">
                                                        <?= $this->protectFromXss($childComment->getUsername()) ?>
                                                    </a>
                                                    <div class="date">
                                                        <?= $this->protectFromXss($childComment->getDateOfWriting()) ?>
                                                    </div>
                                                    <div class="comment-text">
                                                        <?= $this->protectFromXss($childComment->getTextOfComment()) ?>
                                                    </div>
                                                </div>
                                            </article>
                                        </li>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                        </li>
                    <?php endforeach; ?>
                </ul>

                <h2>Оставить комментарий</h2>
                <form action="/add-comment?id=<?= $this->protectFromXss($game->getId()) ?>" method="post">
                    <div class="comment-cont clearfix">
                        <div class="youplay-textarea">
                            <textarea
                                    name="message"
                                    rows="5"
                                    placeholder="Your Comment..."
                            >
                            </textarea>
                        </div>
                        <button class="btn btn-default pull-right">Отправить</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="col-md-3">
            <div class="side-block">
                <h4 class="block-title">Компания</h4>
                <ul class="block-content">
                    <li>
                        <a href="#!">
                            <?= $this->protectFromXss($game->getCompanyObject()->getName()) ?>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="side-block">
                <h4 class="block-title">Жанр</h4>
                <ul class="block-content">
                    <li>
                        <a href="#!"><?= $this->protectFromXss($game->getGenreObject()->getNameOfGenre()) ?></a>
                    </li>
                </ul>
            </div>

            <div class="side-block">
                <h4 class="block-title">Оценка на MetaCritic</h4>
                <ul class="block-content">
                    <li>
                        <a href="#!"><?= $this->protectFromXss($game->getScore()) ?></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>
</body>
</html>
