<?php
/**
 * @var \App\Block\LibraryBlock $this
 */
$playerInfo = $this->getPlayerInfo()[0];
?>

<html>
<head>
    <title>Библиотека</title>
</head>
<body>
<section class="content-wrap">
    <div class="youplay-banner banner-top youplay-banner-parallax small background_diablo">
        <div class="youplay-user-navigation">
            <div class="container">
                <ul>
                    <li>
                        <a href="/player">Профиль</a>
                    </li>
                    <li class="active">
                        <a href="/library">Библиотека</a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="info">
            <div>
                <div class="container youplay-user">
                    <a href="src/image/user-photo.jpg" class="angled-img image-popup">
                        <div class="img">
                            <img src="src/image/user-avatar.jpg" alt="">
                        </div>
                        <i class="fa fa-search-plus icon"></i>
                    </a>

                    <div class="user-data">
                        <h2><?= $playerInfo['username'] ?></h2>
                        <div class="location">
                            <?= $playerInfo['name'] . $playerInfo['surname']; ?>
                        </div>
                        <div class="activity">
                            <div>
                                <div class="num"><?= $playerInfo['fake_hour'] ?></div>
                                <div class="title">Игровых часов</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container youplay-content">
        <div class="row">
            <div class="col-md-9">
                <section class="youplay-features container">
                    <?php foreach($this->getGames() as $game): ?>
                    <a href="/game">
                            <div class="col-md-3 col-xs-12">
                                <div class="feature angled-bg">
                                    <h3><?= $game['name'] ?></h3>
                                </div>
                            </div>

                   <?php endforeach; ?>
                </section>
            </div>
        </div>
    </div>
</section>
</body>
</html>
