<?php
/**
 * @var \App\Block\LibraryBlock $this
 */
$player = $this->getPlayerInfo();
?>

<html>
<head>
    <title>Библиотека</title>
</head>
<body>
<section class="content-wrap">
    <div class="youplay-banner banner-top youplay-banner-parallax small background_diablo">
        <div class="youplay-user-navigation">
            <div class="container">
                <ul>
                    <li>
                        <a href="/player?id=<?= $this->protectFromXss($player->getId()) ?>">
                            Профиль
                        </a>
                    </li>
                    <li class="active">
                        <a href="/library?id=<?= $this->protectFromXss($player->getId()) ?>">
                            Библиотека
                        </a>
                    </li>
                    <li>
                        <a href="/edit-player?id=<?= $this->protectFromXss($player->getId()) ?>">
                            Изменить информацию
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="info">
            <div>
                <div class="container youplay-user">
                    <a href="src/image/user-photo.jpg" class="angled-img image-popup">
                        <div class="img">
                            <img src="src/image/user-avatar.jpg" alt="">
                        </div>
                        <i class="fa fa-search-plus icon"></i>
                    </a>

                    <div class="user-data">
                        <h2><?= $this->protectFromXss($player->getUsername()) ?></h2>
                        <div class="location">
                            <?= $this->protectFromXss($player->getName() . ' ' .  $player->getSurname()); ?>
                        </div>
                        <div class="activity">
                            <div>
                                <div class="num"><?= $this->protectFromXss($player->getFakeHour()) ?></div>
                                <div class="title">Игровых часов</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container youplay-content">
        <div class="row">
            <div class="col-md-9">
                <section class="youplay-features container">
                    <?php foreach($this->getGames() as $game): ?>
                        <a href="/game?id=<?= $this->protectFromXss($game->getId()) ?>">
                                <div class="col-md-3 col-xs-12">
                                    <div class="feature angled-bg">
                                        <h3><?= $this->protectFromXss($game->getName()) ?></h3>
                                    </div>
                                </div>
                        </a>
                   <?php endforeach; ?>
                </section>
            </div>
        </div>
    </div>
</section>
</body>
</html>
