<!DOCTYPE html>
<html>
<head>
    <title>Логин</title>
</head>
<body>
    <section class="content-wrap full youplay-login">

    <div class="youplay-banner banner-top">
      <div class="image" style="background-image: url('../src/image/login-bg.jpg')"></div>

      <div class="info">
        <div>
          <div class="container align-center">
            <div class="youplay-form">
              <h1>Авторизация</h1>
              <form action="/sign-in" method="post">
                <div class="youplay-input">
                  <input type="email" name="mail" placeholder="Email">
                </div>
                <div class="youplay-input">
                  <input type="password" name="password" placeholder="Password">
                </div>
                <button class="btn btn-default db">Login</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>
</html>
