<?php
/**
 * @var \App\Block\MailingBlock $this
 */
?>
<html lang="en">
<head>
    <title>Рассылка</title>
</head>
<body>
    <section class="content-wrap">
        <section class="youplay-banner banner-top big youplay-banner-parallax background__anime_admin">
            <div class="info">
                <div>
                    <div class="container">
                        <div class="main-text neon-text">
                            Mailing
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="youplay-content">
            Рассылка прошла успешно
        </div>

        <a
                class="btn btn-default db"
                style="margin-top: 20px; margin-left: 20px"
                href="/admin-players"
        >
            Вернуться
        </a>


    </section>
</body>
</html>