<?php
/**
 * @var \App\Block\MainBlock $this
 */
$dog = $this->getDog();
?>
<html lang="en">
<head>
    <title>Главная страница</title>
</head>
<body>
    <section class="content-wrap">
        <section class="youplay-banner banner-top big youplay-banner-parallax background_anime">
            <div class="info">
                <div>
                    <div class="container">
                        <div class="main-text neon-text">
                            Orion
                            Games
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="youplay-content">
            <div class="img">
                <img src="<?= $dog['url'] ?>" style="max-width: 30%; max-height: 30%" alt="">
            </div><p></p>
                <?php $i = 0; foreach($this->getAllPlayer() as $player): ?>
                    <?php if ($i == 0): ?>
                        <section class="youplay-features container shop">
                    <?php endif; ?>
                    <?php if ($i == 3): ?>
                        </section>
                        <section class="youplay-features container shop">
                    <?php $i = 0; endif; ?>
                    <a href="/player?id=<?= $this->protectFromXss($player->getId()) ?>">
                        <div class="col-md-3 col-xs-12 shop__element">
                            <div class="feature angled-bg">
                                <h3><?= $this->protectFromXss($player->getUsername()) ?></h3>
                            </div>
                        </div>
                    </a>
                <?php $i++; endforeach; ?>
            </section>
        </div>
    </section>
</body>
</html>