<?php
/**
 * @var \App\Block\MainBlock $this
 */
?>
<html lang="en">
<head>
    <title>Главная страница</title>
</head>
<body>
    <section class="content-wrap">
        <section class="youplay-banner banner-top big youplay-banner-parallax background_anime">
            <div class="info">
                <div>
                    <div class="container">
                        <div class="main-text neon-text">
                            Orion
                            Games
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>
</body>
</html>