<?php
/**
 * @var \App\Block\GameBlock $this
 */
?>

<html>
<head>
    <title>Добавить компанию</title>
</head>
<body>
    <section class="content-wrap">
        <div class="youplay-banner banner-top youplay-banner-parallax small">
            <div class="image" style="background-image: url('/src/image/banner-blog-bg.jpg')">
            </div>

            <div class="info">
                <div>
                    <div class="container">
                        <h1 class="neon-text main-text">Добавить компанию</h1>
                    </div>
                </div>
            </div>

            <div class="youplay-user-navigation">
                <div class="container">
                    <ul>
                        <li>
                            <a href="/companies">Список компаний</a>
                        </li>
                        <li class="active">
                            <a href="/newcompany">Добавить компанию</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container youplay-content">
            <h2 class="mt-0">Информация о компании</h2>
            <p>
            <form action="/addcompany" method="post">
                <div class="youplay-input">
                    <input
                            type="hidden"
                            name="csrf_token"
                            value="<?= $this->getCsrfToken() ?>"
                    >
                </div>
                <div class="youplay-input">
                    <input type="text" name="name" placeholder="Название">
                </div>
                <div class="youplay-input">
                    <input type="text" name="type" placeholder="Тип компании">
                </div>
                <div class="youplay-input">
                    <input type="text" name="address" placeholder="Адрес">
                </div>
                <button class="btn btn-default db">Добавить</button>
            </form>
            </p>
        </div>
    </section>
</body>
</html>