<?php
/**
 * @var \App\Block\GameBlock $this
 */
?>

<html>
<head>
    <title>Добавить игру</title>
</head>
<body>
    <section class="content-wrap">
        <div class="youplay-banner banner-top youplay-banner-parallax small">
            <div class="image" style="background-image: url('/src/image/banner-blog-bg.jpg')">
            </div>

            <div class="info">
                <div>
                    <div class="container">
                        <h1 class="neon-text main-text">Добавить игру</h1>
                    </div>
                </div>
            </div>

            <div class="youplay-user-navigation">
                <div class="container">
                    <ul>
                        <li>
                            <a href="/admin-games">Список игр</a>
                        </li>
                        <li class="active">
                            <a href="/newgame">Добавить игру</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container youplay-content">
            <h2 class="mt-0">Информация об игре</h2>
            <p>
            <form action="/addgame" method="post">
                <div class="youplay-input">
                    <input
                            type="hidden"
                            name="csrf_token"
                            value="<?= htmlspecialchars($this->getCsrfToken()) ?>"
                    >
                </div>
                <div class="youplay-input">
                    <input type="text" name="name" placeholder="Название">
                </div>
                <div class="youplay-input">
                    <input type="text" name="company" placeholder="Компания">
                </div>
                <div class="youplay-input">
                    <input type="text" name="genre" placeholder="Жанр">
                </div>
                <div class="youplay-input">
                    <input type="date" name="year_of_release">
                </div>
                <div class="youplay-input">
                    <input type="text" name="score" placeholder="Оценка">
                </div>
                <div class="comment-cont clearfix">
                    <div class="youplay-textarea">
                        <textarea
                            name="description"
                            rows="5"
                            placeholder="Описание игры"
                        >
                        </textarea>
                    </div>
                </div>
                <button class="btn btn-default db">Добавить</button>
            </form>
            </p>
        </div>
    </section>
</body>
</html>