<?php
/**
 * @var \App\Block\PlayerBlock $this
 */

$player = $this->getPlayerInfo();
?>

<html>
<head>
    <title>Профиль</title>
</head>
<body>
<section class="content-wrap">
    <div class="youplay-banner banner-top youplay-banner-parallax small background_diablo">
        <div class="youplay-user-navigation">
            <div class="container">
                <ul>
                    <li class="active">
                        <a href="/player?id=<?= $this->protectFromXss($player->getId()) ?>">
                            Профиль
                        </a>
                    </li>
                    <li>
                        <a href="/library?id=<?= $this->protectFromXss($player->getId()) ?>">
                            Библиотека
                        </a>
                    </li>
                    <li>
                        <a href="/edit-player?id=<?= $this->protectFromXss($player->getId()) ?>">
                            Изменить информацию
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="info">
            <div>
                <div class="container youplay-user">
                    <a href="src/image/user-photo.jpg" class="angled-img image-popup">
                        <div class="img">
                            <img src="src/image/user-avatar.jpg" alt="">
                        </div>
                        <i class="fa fa-search-plus icon"></i>
                    </a>

                    <div class="user-data">
                        <h2><?= $this->protectFromXss($player->getUsername()) ?></h2>
                        <div class="location">
                            <?= $this->protectFromXss($player->getName() . ' ' . $player->getSurname()) ?>
                        </div>
                        <div class="activity">
                            <div>
                                <div class="num"><?= $this->protectFromXss($player->getFakeHour()) ?></div>
                                <div class="title">Игровых часов</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container youplay-content">
        <div class="row">
            <div class="col-md-9">
                <h3 class="mt-0 mb-20">Информация</h3>
                <table class="table table-bordered">
                    <tbody>
                    <tr>
                        <td style="width: 200px;">
                            <p>ФИО</p>
                        </td>
                        <td>
                            <p>
                                <?= $this->protectFromXss($player->getName() . ' ' . $player->getSurname()) ?>
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>Ник</p>
                        </td>
                        <td>
                            <p>
                                <?= $this->protectFromXss($player->getUsername()) ?>
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>Дата регистрации</p>
                        </td>
                        <td>
                            <p>
                                <?= $this->protectFromXss($player->getDateOfRegistration()) ?>
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>Игровые часы</p>
                        </td>
                        <td>
                            <p>
                                <?= $this->protectFromXss($player->getFakeHour()) ?>
                            </p>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
</body>
</html>
