<!DOCTYPE html>
<html>
<head>
    <title>Регистрация</title>
</head>
<body>
    <section class="content-wrap full youplay-login">

    <div class="youplay-banner banner-top">
      <div class="image" style="background-image: url('/image/login-bg.jpg')"></div>

      <div class="info">
          <div class="container align-center">
            <div class="youplay-form">
              <h1>Регистрация</h1>
              <form action="/add-player" method="post">
                  <div class="youplay-input">
                      <input
                              type="text"
                              name="name"
                              placeholder="Имя"
                      >
                  </div>
                  <div class="youplay-input">
                      <input
                              type="text"
                              name="surname"
                              placeholder="Фамилия"
                      >
                  </div>
                  <div class="youplay-input">
                      <input
                              type="text"
                              name="username"
                              placeholder="Ник"
                      >
                  </div>
                  <div class="youplay-input">
                      <input
                              type="email"
                              name="mail"
                              placeholder="Email"
                      >
                  </div>
                  <div class="youplay-input">
                      <div class="youplay-input">
                      <input type="password" name="password" placeholder="Password">
                      </div>
                  </div>
                  <button class="btn btn-default db">Register</button>
              </form>
            </div>
          </div>
      </div>
    </div>
  </section>
</body>
</html>
